CREATE DATABASE IF NOT EXISTS application_db DEFAULT CHARACTER SET utf8;
CREATE DATABASE IF NOT EXISTS crawl_db DEFAULT CHARACTER SET utf8;
CREATE DATABASE IF NOT EXISTS interface_db DEFAULT CHARACTER SET utf8;
CREATE DATABASE IF NOT EXISTS cleandata_db DEFAULT CHARACTER SET utf8;
CREATE DATABASE IF NOT EXISTS rule_db DEFAULT CHARACTER SET utf8;
CREATE DATABASE IF NOT EXISTS archive_db DEFAULT CHARACTER SET utf8;
GRANT ALL PRIVILEGES ON *.* TO 'risk'@'%' IDENTIFIED BY 'riskpassword' WITH GRANT OPTION;
FLUSH PRIVILEGES;
